### PR TITLE
Fix Dependencies

### PR DESCRIPTION
**Pull request by genio**
The dependencies in this dist are a bit out of date and some are missing. In particular, ```Devel::Pragma``` dropped the ```on_require``` function in version 1.000000.

These problems prevent the dist from building/testing. To get around this, a few changes were made:

* Add a cpanfile for easier management of prereqs.
* Add a prereq report for testers to aid in debugging.
* Get rid of usage of Devel::Param::on_require as that was dropped quite some time ago (v1.0.0).
* Update ppport.h with latest.

Hope that helps.

### CODE REVIEW

**Comment by chocolateboy** [comment]
Thanks!

Are you using this module? I've been planning to remove it from CPAN for a while as it's a [pain to maintain](https://rt.cpan.org/Public/Bug/Display.html?id=100710#txn-1439112), and it only appears to be used by [two experimental modules](http://deps.cpantesters.org/depended-on-by.pl?dist=Method-Lexical-0.30) (cc @tobyink).

**Comment by genio** [comment]
I'm not, no.  I received the module in the [Pull Request Challenge](http://cpan-prc.org/) for this month.  If it's a pain to maintain, maybe deletion or putting it up for adoption would be best (or direct handoff to @tobyink )?

**Comment by tobyink** [comment]
I quite like this module, even if it's still way too experimental for using in stable software. I'd be happy to take over the module if it needs a new maintainer.

**Comment by chocolateboy** [comment]
Awesome! I've made you a collaborator on this repo (but feel free to fork it and maintain it under your own account if you prefer), and the primary maintainer on PAUSE.

Good luck!

**Pull request merged**
